application: metafight-scraper
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- deferred: on
- admin_redirect: on
- appstats: on

handlers:
- url: /.*
  script: app.app

libraries:
- name: webapp2
  version: "latest"
